name: ladder_api
description: A web server application to manage sports ladders
version: 0.0.1
author: Justin Doak <justin@jhdoak.com>

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  aqueduct: ^2.5.0+1

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
